### ISSUE TITLE
Añadir jLasni a los repositorios de Maven

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/jLasni#7]
Propuesto por @zerasul

**Comment by JuanjoSalvador** [comment]
Esto está mavenizado ya, ¿no @zerasul?

**Comment by zerasul** [comment]
Es correcto; esta mavenizado... pero no esta subido a los repositorios de maven central. Hay que preparar el Pom y subirlo a MavenCentral.

[Guia de subida](https://maven.apache.org/guides/mini/guide-central-repository-upload.html)

**Comment by JuanjoSalvador** [comment]
Pues lo añado como nueva issue.
