### ISSUE TITLE
Subir a MavenCentral

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/jLasni#8]
> esta mavenizado... pero no esta subido a los repositorios de maven central. Hay que preparar el Pom y subirlo a MavenCentral.
> https://github.com/JuanjoSalvador/jLasni/issues/7#issuecomment-248912460

[Guía de subida](https://maven.apache.org/guides/mini/guide-central-repository-upload.html)

**Comment by zerasul** [comment]
No es a maven central pero https://github.com/zerasul/lasnimvnrepository ya esta en un repo. así que no se si decirte que fixed #8

**Comment by JuanjoSalvador** [comment]
Yo diría que si, podemos cerrarla
